GET http://localhost:3000/api/v1/acting-credits

###

GET http://localhost:3000/api/v1/acting-credits/60b4f296307467376c29df8d

###

POST http://localhost:3000/api/v1/acting-credits
Content-Type: application/json

{
    "role": "IQ",
    "company":"CenterSfgftage",
    "show":"HairSpray"
}

###

DELETE http://localhost:3000/api/v1/acting-credits/60b4f296307467376c29df8d